with-expecter: false
packages:
    github.com/jfelipearaujo-org/lambda-login/internal/providers/interfaces:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/providers/interfaces/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Provider)"
    github.com/jfelipearaujo-org/lambda-login/internal/database/interfaces:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/database/interfaces/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Database)"
    github.com/jfelipearaujo-org/lambda-login/internal/hashs/interfaces:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/hashs/interfaces/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Hasher)"
    github.com/jfelipearaujo-org/lambda-login/internal/token/interfaces:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/token/interfaces/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Token)"